### ISSUE TITLE
Unable to install veeamsnap-5.0.0.4318 on Debian 10.8

### ISSUE THREAD

**Issue by Shadok** [veeam/veeamsnap#16]
Hello,

I have an error with latest veeamsnap package (official veeam repo) on my NAS :
- Kernel : 5.10.0-0.bpo.3-amd64
- OS : OpenMediaVault 5.6.2 (Debian 10.8)
- Package : veeamsnap-5.0.0.4318

> Loading new veeamsnap-5.0.0.4318 DKMS files...
> Building for 5.10.0-0.bpo.3-amd64
> Building initial module for 5.10.0-0.bpo.3-amd64
> Error! Bad return status for module build on kernel: 5.10.0-0.bpo.3-amd64 (x86_64)
> Consult /var/lib/dkms/veeamsnap/5.0.0.4318/build/make.log for more information.

Here's the make.log :
```
DKMS make.log for veeamsnap-5.0.0.4318 for kernel 5.10.0-0.bpo.3-amd64 (x86_64)
dimanche 7 mars 2021, 13:03:17 (UTC+0100)
make : on entre dans le répertoire « /usr/src/linux-headers-5.10.0-0.bpo.3-amd64 »
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/log.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/mem_alloc.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/sparse_bitmap.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/container.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/container_spinlocking.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/queue_spinlocking.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/bitmap_sync.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/page_array.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/rangelist.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/rangelist_ex.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/rangevector.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.o
/var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.c: In function ‘blk_dev_open’:
/var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.c:17:15: error: implicit declaration of function ‘bdget’; did you mean ‘dget’? [-Werror=implicit-function-declaration]
     blk_dev = bdget( dev_id );
               ^~~~~
               dget
/var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.c:17:13: warning: assignment to ‘struct block_device *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
     blk_dev = bdget( dev_id );
             ^
/var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.c:26:16: error: implicit declaration of function ‘blkdev_get’; did you mean ‘blkdev_put’? [-Werror=implicit-function-declaration]
     refCount = blkdev_get( blk_dev, FMODE_READ | FMODE_WRITE, NULL );
                ^~~~~~~~~~
                blkdev_put
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_direct.o
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-5.10.0-0.bpo.3-common/scripts/Makefile.build:284: /var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.o] Error 1
make[2]: *** Attente des tâches non terminées....
make[1]: *** [/usr/src/linux-headers-5.10.0-0.bpo.3-common/Makefile:1817: /var/lib/dkms/veeamsnap/5.0.0.4318/build] Error 2
make: *** [/usr/src/linux-headers-5.10.0-0.bpo.3-common/Makefile:185: __sub-make] Error 2
make : on quitte le répertoire « /usr/src/linux-headers-5.10.0-0.bpo.3-amd64 »
```

**Comment by Shadok** [comment]
It seems related to #10.

**Comment by CodeImp** [comment]
Duplicate of #10.
Exactly.
You can use veeamsnap from the experimental [branch](https://github.com/veeam/veeamsnap/tree/experimental) with [blk_interposer](https://github.com/veeam/veeamsnap/tree/experimental/blk_interposer) for kernels 5.9, 5.10 & 5.11.
We continue to work on adding blk_interposer to the kernel. The latest [patch for 5.12-rc1](https://patchwork.kernel.org/project/linux-block/cover/1614774618-22410-1-git-send-email-sergei.shtepa@veeam.com/) was sent.

**Comment by Shadok** [comment]
Thanks, but there is no hurry in my case, take your time :)
