### ISSUE TITLE
Veeamsnap not installing on Debian 11

### ISSUE THREAD

**Issue by 541263** [veeam/veeamsnap#25]
Can't install veeamsnap-5.0.0.4318 after upgrading to Debian 11 Bullseye.

Error! Bad return status for module build on kernel: 5.10.0-8-amd64 (x86_64)

make: Entering directory '/usr/src/linux-headers-5.10.0-8-amd64'
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/log.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/mem_alloc.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/sparse_bitmap.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/container.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/container_spinlocking.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/queue_spinlocking.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/bitmap_sync.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/page_array.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/rangelist.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/rangelist_ex.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/rangevector.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_direct.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_redirect.o
  CC [M]  /var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_deferred.o
/var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.c: In function ‘blk_dev_open’:
/var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.c:17:15: error: implicit declaration of function ‘bdget’; did you mean ‘dget’? [-Werror=implicit-function-declaration]
   17 |     blk_dev = bdget( dev_id );
      |               ^~~~~
      |               dget
/var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.c:17:13: warning: assignment to ‘struct block_device *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
   17 |     blk_dev = bdget( dev_id );
      |             ^
/var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.c:26:16: error: implicit declaration of function ‘blkdev_get’; did you mean ‘blkdev_put’? [-Werror=implicit-function-declaration]
   26 |     refCount = blkdev_get( blk_dev, FMODE_READ | FMODE_WRITE, NULL );
      |                ^~~~~~~~~~
      |                blkdev_put
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-5.10.0-8-common/scripts/Makefile.build:284: /var/lib/dkms/veeamsnap/5.0.0.4318/build/blk_util.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-5.10.0-8-common/Makefile:1845: /var/lib/dkms/veeamsnap/5.0.0.4318/build] Error 2
make: *** [/usr/src/linux-headers-5.10.0-8-common/Makefile:185: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-5.10.0-8-amd64'

**Comment by Xav-Pe** [comment]
Yeah related to https://github.com/veeam/veeamsnap/issues/10 . 1 year without a fix.

**Comment by 541263** [comment]
> Yeah related to #10 . 1 year without a fix.

well... shit

**Comment by Xav-Pe** [comment]
As you say. Bullseye is now stable, which means veeamsnap is now broken.

**Comment by veeam** [comment]
> As you say. Bullseye is now stable, which means veeamsnap is now broken.

'Broken' is not really a correct terms to describe a situation when something is used not as intended - Debian 11 uses kernel version which is not on the [list of kernels that veeamsnap is compatible with.](https://github.com/veeam/veeamsnap#compatibility)

Good news though - we've found a way to support even that, so be patient, please.

**Comment by veeam** [comment]
> As you say. Bullseye is now stable, which means veeamsnap is now broken.

'Broken' is not really a correct terms to describe a situation when something is used out of it's support scope.
Debian 11 uses kernel version which is not on the list of kernels that veeamsnap fully supports (mind the [experimental support part](https://github.com/veeam/veeamsnap/tree/experimental#compatibility)).

Good news though - we've found a way to support even that, so be patient, please.

Thanks!

**Comment by HNGamingUK** [comment]
You will be happy to know that since the release of 5.0.1 (released today) veeamsnap now supports up to Kernel 5.13 from "master"

**Comment by veeam** [comment]
Reading system requirements before installing products will make you more happy. You should try ;)

________________________________

**Comment by 541263** [comment]
> Reading system requirements before installing products will make you more happy. You should try ;)

You still don't support Debian 11 and are happy about it? :(

**Comment by veeam** [comment]
That is not a correct statement that shows me you STILL didn't bother reading system requirements.
________________________________

**Comment by veeam** [comment]
You’re missing software pre-requisites. Search the System Requirements document for “Debian 11”:
https://helpcenter.veeam.com/docs/agentforlinux/userguide/system_requirements.html?ver=50
